name: Deploy
on:
    push:
        tags:
            - 'v[\d+]\.[\d+]\.[\d+]'

jobs:
    deploy:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
              name: Checkout
              with:
                path: f-22a

            - name: Clean Project
              working-directory: f-22a
              run: |
                Set-ItemProperty -Path .git -Name Attributes -Value Normal
                Remove-Item -Path .git -Recurse -Force -ErrorAction SilentlyContinue
                Remove-Item -Path .github -Recurse -Force -ErrorAction SilentlyContinue
                Remove-Item -Path .gitignore -Force -ErrorAction SilentlyContinue
                Remove-Item -Path .gitattributes -Force -ErrorAction SilentlyContinue
                Remove-Item -Path README.md -Force -ErrorAction SilentlyContinue
                Remove-Item -Path CONTRIBUTING.md -Force -ErrorAction SilentlyContinue

            - name: Compress Files
              run: Compress-Archive -Path f-22a -DestinationPath f-22a.zip

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                files: f-22a.zip